### PR TITLE
Updating shipdist packages for Ubuntu24

### PR DESCRIPTION
**Pull request by antonioiuliano2**
Dear all,

I have made a first ShipSoft build with Ubuntu24.4 LTS

With respect to the previous Ubuntu22, the new version by default uses the more recent GCC13.3 and Python3.12.
Therefore, some packages lead to compilation errors, solved by updating them to compatible versions.

You can find all the details in the attached file
[Notes_Build_Ubuntu24_04.md](https://github.com/user-attachments/files/21986416/Notes_Build_Ubuntu24_04.md)

The affected packages are:

- boost: 1.70.0 -> 1.74.0
- Geant4: 10.7.3 -> 11.3.0
- VMC: 1.1-p1 -> 2.1
- GEANT4_VMC: 5-4 -> 6-7
- VGM: 4.9 -> 5.1
- pip (in Python Modules): 21.3.1 -> 24.3.1

Please let me know if anyone still needs the old versions of these packages. In that case, I may try a build with the shipdist Python and GCC-Toolchain, instead of taking them from the system.

Best Regards,
Antonio

### CODE REVIEW

**Comment by antonioiuliano2** [comment]
P.S. I just did git rebase from origin/main to fix the conflicts (basically pip being 25.0.1 instead of 24.3.1).
I have tested build again for safety, no issue.
Please let me know when I can force-push them here.

**Comment by olantwin** [comment]
Please go ahead and push.

**Comment by olantwin** [comment]
My plan is to update these versions also for SLC9, one by one to get the same stack to work on both.

For GEANT4, it would be great to have input from the physics group.

**Comment by olantwin** [comment]
Boost will be updated in #144
